image:
  repository: arjunvkrishna/kafka
  tag: "1.0.1"

brokers:
  - id: 0
  - id: 1
  - id: 2

kafka:
  quorumVoters: "0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093"
  clusterId: "abcdefghijklmnopqrstuv"
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  transactionStateLogMinISR: 2
  numPartitions: 32
  logRetentionHours: 600000

resources:
  requests:
    memory: "50Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClass: "hostpath"
  size: 8Gi

service:
  kafka0:
    type: NodePort
    nodePort: 32000
  kafka1:
    type: ClusterIP
  kafka2:
    type: ClusterIP
