apiVersion: v1
kind: Service
metadata:
  name: kafka-{{ .Values.kafka.nodeIds }}
  labels:
    app: kafka-{{ .Values.kafka.nodeIds }}
spec:
  type: {{ if eq .Values.kafka.nodeIds 0 }}{{ .Values.service.kafka0.type }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: 9092
      targetPort: 9092
      {{- if eq .Values.kafka.nodeIds 0 }}
      nodePort: {{ .Values.service.kafka0.nodePort }}
      {{- end }}
      name: kafka-{{ .Values.kafka.nodeIds }}
  selector:
    app: kafka-{{ .Values.kafka.nodeIds }}
